ALTER TABLE
    BIGDATA.SIAIC
ADD
    CONSTRAINT SYS_C0091397 PRIMARY KEY (CD_VUELO) USING INDEX SYS_C0091397 ENABLECREATE TABLE BIGDATA.SIAIC (
     FECHA_REAL DATE,
     CD_VUELO VARCHAR2(50 BYTE) NOT NULL,
     ID_VUELO VARCHAR2(50 BYTE),
     ID_VUELO_PROG VARCHAR2(50 BYTE),
     ID_VUELO_REAL VARCHAR2(50 BYTE),
	 CIA VARCHAR2(50 BYTE),
	 VUELO VARCHAR2(50 BYTE),
	 FLOTA_PROGRAMADA VARCHAR2(50 BYTE),
	 FLOTA_REAL VARCHAR2(50 BYTE),
	 PROPIETARIO_VUELO VARCHAR2(50 BYTE),
	 FECHA_SALIDA_PROG DATE,
	 FECHA_SALIDA_REAL DATE,
	 MINUTOS_RETRASO NUMBER,
	 TRAMO_PROGRAMADO VARCHAR2(50 BYTE),
	 TRAYECTO_PROGRAMADO VARCHAR2(50 BYTE),
	 TRAMO_REAL VARCHAR2(50 BYTE),
	 TRAYECTO_REAL VARCHAR2(50 BYTE),
	 SECTOR_REAL VARCHAR2(50 BYTE),
	 OPERADOR_INFORMES VARCHAR2(50 BYTE),
	 ORIGEN_PROG VARCHAR2(50 BYTE),
	 DESTINO_PROG VARCHAR2(50 BYTE),
	 ORIGEN_REAL VARCHAR2(50 BYTE),
	 DESTINO_REAL VARCHAR2(50 BYTE),
	 SECTOR VARCHAR2(100 BYTE),
	 MATRICULA_PROGRAMADA VARCHAR2(50 BYTE),
	 MATRICULA_REAL VARCHAR2(50 BYTE),
	 FRANJA_HORARIA VARCHAR2(50 BYTE),
	 ORIGEN_VUELO VARCHAR2(50 BYTE),
	 ESTADO_VUELO VARCHAR2(50 BYTE),
	 TIPO_RETRASO_SALIDA VARCHAR2(50 BYTE),
	 TIPO_RETRASO_LLEGADA VARCHAR2(50 BYTE),
	 OPERADOR_PROGRAMADO VARCHAR2(50 BYTE),
	 OPERADOR_REAL VARCHAR2(50 BYTE),
	 TRANSPORTISTA_KEOPS VARCHAR2(50 BYTE),
	 TIEMPO_VUELO NUMBER,
	 TIEMPO_BLOQUE NUMBER,
	 ASIENTOS_OFERTADOS NUMBER,
	 NUMERO_ADULTOS_PAGO NUMBER,
	 NUMERO_ADULTOS_FREE NUMBER,
	 NUMERO_CHILD_PAGO NUMBER,
	 NUMERO_CHILD_FREE NUMBER,
	 NUMERO_INFANT NUMBER,
	 NUMERO_CHARTER NUMBER,
	 NU_EXC_EQUIPAJE NUMBER,
	 NU_MCO NUMBER,
	 NU_OTROS NUMBER,
	 INGRESOS_ADULTOS_PAGO NUMBER,
	 INGRESOS_ADULTOS_FREE NUMBER,
	 INGRESOS_CHILD_PAGO NUMBER,
	 INGRESOS_CHILD_FREE NUMBER,
	 INGRESOS_INFANT NUMBER,
	 INGRESOS_CHARTER NUMBER,
	 INGRESOS_EQUIPAJE NUMBER,
	 INGRESOS_MCO NUMBER,
	 INGRESOS_OTROS NUMBER,
	 INGRESOS_TASAS_QV NUMBER,
	 INGRESOS_TASAS_RS NUMBER,
	 KG_EQUIPAJE NUMBER,
	 KG_MERCANCIA_PAGO NUMBER,
	 KG_MERCANCIA_FREE NUMBER,
	 KG_CORREO NUMBER,
	 INGRESOS_NERCANCIA_PAGO NUMBER,
	 INGRESOS_MERCANCIA_FREE NUMBER,
	 INGRESOS_CORREO NUMBER,
	 PASAJEROS_TRANSPORTADOS NUMBER,
	 OCUPACION NUMBER,
	 VUELO_FUTURO VARCHAR2(50 BYTE),
	 CAPACIDAD_MAXIMA_PROG NUMBER,
	 CAPACIDAD_MAXIMA_REAL NUMBER
    ) LOGGING TABLESPACE BIG_DATA PCTFREE 10 INITRANS 1 STORAGE (
        INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    ) NOCOMPRESS NOPARALLELCREATE UNIQUE INDEX BIGDATA.SYS_C0091397 ON BIGDATA.SIAIC (CD_VUELO ASC) LOGGING TABLESPACE BIG_DATA PCTFREE 10 INITRANS 2 STORAGE (
        INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
    ) NOPARALLEL



CREATE TABLE BIGDATA.VOLADOS (
     CIA VARCHAR2(3 BYTE),
     BILLETE VARCHAR2(50 BYTE),
     LOCALIZADOR VARCHAR2(50 BYTE),
     FECHA_COMPRA DATE,
     ID_BILLETE VARCHAR2(50 BYTE),
     ID_VUELO VARCHAR2(50 BYTE),
     ID_VENTA_VOLADOS VARCHAR2(50 BYTE),
     TRANSPORTISTA VARCHAR2(50 BYTE),
     VUELO VARCHAR2(50 BYTE),
     FECHA_VUELO DATE,
     IMPORTE_TOTAL NUMBER,
     IMPORTE_PAGADO NUMBER,
     TIPO_TRAMO VARCHAR2(50 BYTE),
     CLASE VARCHAR2(50 BYTE),
     FAREBASIS VARCHAR2(50 BYTE),
     TIPO_PAX VARCHAR2(50 BYTE),
     TIPO_PERSONA VARCHAR2(50 BYTE),
     TRANSPORTADO VARCHAR2(50 BYTE),
     VUELO_GUAGUA VARCHAR2(50 BYTE),
     ORIGEN VARCHAR2(50 BYTE),
     DESTINO VARCHAR2(50 BYTE),
     FECHA_CARGA DATE
) LOGGING TABLESPACE BIG_DATA PCTFREE 10 INITRANS 1 STORAGE (
    INITIAL 237568 NEXT 237568 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
) NOCOMPRESS NOPARALLELCREATE INDEX BIGDATA.INDEX_VOLADOS ON BIGDATA.VOLADOS (BILLETE ASC) LOGGING TABLESPACE BIG_DATA PCTFREE 10 INITRANS 2 STORAGE (
    INITIAL 237568 NEXT 237568 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
) NOPARALLEL


CREATE TABLE BIGDATA.CHECKIN (
    BILLETE VARCHAR2(100 BYTE),
    ID_BILLETE VARCHAR2(100 BYTE),
    TIPO_ACEPTADO VARCHAR2(50 BYTE),
    BOARDED VARCHAR2(50 BYTE),
    TIPO_PRIMER_CHECKIN VARCHAR2(50 BYTE),
    ESTADO VARCHAR2(50 BYTE),
    FECHA_FACTURACION DATE,
    EQUIPAJE VARCHAR2(2 BYTE),
    PESO_TOTAL NUMBER,
    UNIDAD VARCHAR2(2 BYTE),
    FECHA_EQUIPAJE DATE,
    FECHA_VUELO DATE,
    ANTELACION_CHECKIN NUMBER,
    ANTELACION_EQUIPAJE NUMBER,
    TARJETA VARCHAR2(100 BYTE),
    USO_TARJETA VARCHAR2(100 BYTE),
    FECHA_CARGA DATE,
    ID_MALETA VARCHAR2(100 BYTE),
    ORIGEN VARCHAR2(100 BYTE),
    DESTINO VARCHAR2(100 BYTE)
) LOGGING TABLESPACE BIG_DATA PCTFREE 10 INITRANS 1 STORAGE (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
) NOCOMPRESS NOPARALLELCREATE INDEX BIGDATA.INDEX_CHECKIN ON BIGDATA.CHECKIN (BILLETE ASC) LOGGING TABLESPACE BIG_DATA PCTFREE 10 INITRANS 2 STORAGE (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
) NOPARALLEL


CREATE TABLE BIGDATA.AEROPUERTO_MERCADO (
    AEROPUERTO VARCHAR2(3 BYTE),
    MERCADO VARCHAR2(20 BYTE),
    SISTEMA_BINTER NUMBER(1, 0)
) LOGGING TABLESPACE BIG_DATA PCTFREE 10 INITRANS 1 STORAGE (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
) NOCOMPRESS NOPARALLEL


CREATE TABLE BIGDATA.DIAS_FESTIVOS (
    FECHA DATE NOT NULL,
    DESCR VARCHAR2(50 BYTE)
) LOGGING TABLESPACE BIG_DATA PCTFREE 10 INITRANS 1 STORAGE (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT
) NOCOMPRESS NOPARALLEL


CREATE VIEW BIGDATA.CHECKIN_MOSTRADOR_ACEPTADOS AS
SELECT
    "BILLETE",
    "ID_BILLETE",
    "TIPO_ACEPTADO",
    "BOARDED",
    "TIPO_PRIMER_CHECKIN",
    "ESTADO",
    "FECHA_FACTURACION",
	    "EQUIPAJE",
	    "PESO_TOTAL",
	    "UNIDAD",
	    "FECHA_EQUIPAJE",
	    "FECHA_VUELO",
	    "ANTELACION_CHECKIN",
	    "ANTELACION_EQUIPAJE",
	    "TARJETA",
	    "USO_TARJETA"
	FROM
	    checkin
	WHERE
	    ESTADO = 'ACEPTADO'
	    AND TIPO_ACEPTADO = 'MOSTRADOR AEROPUERTO'